Лабораторная работа №5 Лещенко Сергей P33212
dorooleg/ydb pull request #1
Opened 2023-06-02 18:59 UTC by lezchook

2023-06-02 23:04 UTC, dorooleg requested changes

2023-06-03 00:48 UTC, lezchook commented on tools/actor_model/events.h
> +    struct TEvPoisonPill : NActors::TEventLocal<TEvPoisonPill, EvDiscoveryResponse> {};
Сделал

2023-06-03 00:48 UTC, lezchook commented on tools/actor_model/events.h
> +    struct TEvDone : NActors::TEventLocal<TEvDone, EvDiscoveryResponse> {};
Исправил

2023-06-03 00:48 UTC, lezchook commented on tools/actor_model/actors.h
> +THolder<NActors::IActor> CreateTMaximumPrimeDevisorActor(int64_t value, const auto readActor, const NActors::TActorId writeActor);
fixed

2023-06-03 00:49 UTC, lezchook commented on tools/actor_model/actors.cpp
> +    int64_t CurrentState_first;
fixed

2023-06-03 00:49 UTC, lezchook commented
Внес изменения по каждому замечанию

2023-06-10 00:02 UTC, dorooleg commented
lgtm

2023-08-24 16:06 UTC, closed without merging