Марфутенко P33202 Dockerfile
dorooleg/ydb pull request #60
Opened 2024-05-24 20:54 UTC by PetrMKO

Пр на добавление докерфайла. 

Так как далеко не всем интересно как с этим вообще работать, я постарался написать самую внятную инструкцию.

Для людей, кто не боится писать mkdir добавил вариант как собрать все и не ждат по 20 минут при каждом запуске контейнера.

2024-05-24 21:13 UTC, dorooleg requested changes

2024-05-24 21:13 UTC, dorooleg commented on Dockerfile
> +RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
а ее зачем менять? На что это влияет?

2024-05-24 21:13 UTC, dorooleg commented on Dockerfile
> +FROM ubuntu:22.04
а почему на верхнем уровне расположен файл, а не в tools/actor_model?

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +В проекте есть докерфайл, с помощью которого можно осуществлять сборку. Протестирован на windows и macOS (работает только на процессорах intell).
докерфайл -> Dockerfile
intell -> intel

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +1. Клоним ваш форк
Клоним -> Клонируем

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +2. Переходим в него и собираем контейнер
Давай явно напишем в какой директории вызывать, а то могут не понять

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +3. Далее запускаем контейнер(не меняйте пути, там будет папка для билда). При запуске в контейнере прогоняется прогоняется cmake и ninja, поэтому собираться будет долго. Лучше сначала запустить конте
контейнер( -> контейнер (

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +3. Далее запускаем контейнер(не меняйте пути, там будет папка для билда). При запуске в контейнере прогоняется прогоняется cmake и ninja, поэтому собираться будет долго. Лучше сначала запустить конте
папка -> директория, а то могут закидать :)

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +3. Далее запускаем контейнер(не меняйте пути, там будет папка для билда). При запуске в контейнере прогоняется прогоняется cmake и ninja, поэтому собираться будет долго. Лучше сначала запустить конте
прогоняется прогоняется -> прогоняется

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +3. Далее запускаем контейнер(не меняйте пути, там будет папка для билда). При запуске в контейнере прогоняется прогоняется cmake и ninja, поэтому собираться будет долго. Лучше сначала запустить конте
контейнер а -> контейнер, а

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +sudo docker run -v $(pwd):/home/ydbwork/ydb --rm -it actor_model
давай отдельно для windows подготовим команду, там нету $(pwd), там нужен %cd%

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +4. После запуска контейнера вы будете в папку build, от туда можно компилировать и запускать ваш код с помощью команд:
папку -> директории

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +## Если планируете запускать контейнер несколько раз, а каждый раз ждать ждать проверки не хотите
Ускорение перезапуска контейнера несколько раз

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +По сути самая долгая часть в запуске контейнера это запуск cmake и проверки от ninja. Если сохранить лоакльно папку build, то далее запуск контейнера будет сильно быстрее, но понадобятся дополнительн
это запуск -> это
лоакльно -> локально
дополнительные манипуляции локально -> дополнительные локальные манипуляции

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +1. Создадим папку ydbwork и в ней папку build, после чего перейдем в нее
папку -> директорию

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +#RUN mkdir -p /home/ydbwork/build
#RUN -> # RUN
#CMD -> # CMD

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +5. Вернемся в папку ydbwork и запустим контейнер
папку -> директорию

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +sudo docker run -v $(pwd):/home/ydbwork --rm -it actor_model
аналогично для windows лучше отдельно команду привести

2024-05-24 21:13 UTC, dorooleg commented on tools/actor_model/README.md
> +6. Внтури контейнера перейдем в папку /home/ydbwork/build, внутри нее прогоним cmake и ninja
папку -> директорию
/home/ydbwork/build, внутри нее прогоним -> /home/ydbwork/build, а внутри нее запустим

2024-05-24 21:23 UTC, PetrMKO commented on Dockerfile
> +RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
Ни на что, это просто чтобы питон не задавал вопрос о зоне времени и установке не висла на этом вопросе

2024-05-24 21:24 UTC, PetrMKO commented on Dockerfile
> +FROM ubuntu:22.04
Удобно запускать контейнер с этого уровня, иначе надо будет в команде docker run прописывать пути типа ../../..

2024-05-24 21:38 UTC, PetrMKO commented on tools/actor_model/README.md
> +sudo docker run -v $(pwd):/home/ydbwork/ydb --rm -it actor_model
Сейчас проверили на windows через powerShellработает вот такая команда
docker run -v ${PWD}:/home/ydbwork/ydb --rm -it actor_model

2024-05-24 21:49 UTC, dorooleg commented on tools/actor_model/README.md
> +sudo docker run -v $(pwd):/home/ydbwork/ydb --rm -it actor_model
часто студенты только cmd умеют использовать, уже натыкались на это. Давай для cmd тоже добавим с %cd%

2024-05-24 21:52 UTC, dorooleg commented on Dockerfile
> +FROM ubuntu:22.04
Проблему понял, конечно это менее правильно в корень запихивать, но для студенческой ветки пойдет. Оставляем так тогда

2024-05-24 21:53 UTC, dorooleg commented on tools/actor_model/README.md
> +## Ускорения перезапуска контейнера
Ускорения -> Ускорение

2024-05-24 21:54 UTC, dorooleg commented on tools/actor_model/README.md
> +```(bash)
для windows тут забыл добавить

2024-05-25 08:29 UTC, dorooleg approved these changes

2024-05-25 08:29 UTC, merged